 export default {
	GET_USERS: "GET_USERS",
	GET_QUESTIONS: "GET_QUESTIONS",
	 CURRENT_USER: "CURRENT_USER",
	 SAVE_QUESTION_ANSWER: "SAVE_QUESTION_ANSWER",
	 SAVE_QUESTIONS: "SAVE_QUESTIONS",
	 SAVE_CURRENT_QUESTION: "SAVE_CURRENT_QUESTION"
};
